apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: jenkins-pv
  resources:
    requests:
      storage: 10Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-pv
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
